sudo: required
services:
  - docker

before_install:
  - docker build -t krisshatts/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true krisshatts/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Dockerreact"
  env: "Dockerreact-env"
  bucket-name: "elasticbeanstalk-us-east-2-582982764558"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
